spring.application.name=schoolerp

#database
spring.datasource.url=jdbc:postgresql://localhost:5432/schoolerp_001
spring.datasource.username= postgres
spring.datasource.password= postgres

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = update


#default query
spring.sql.init.data-locations=classpath:sql/admission-fee-data.sql
spring.sql.init.mode=always

#debug=true
logging.level.root=INFO
logging.file.name=logs/spring-schoolerp.log
#logging.level.org.springframework.security=DEBUG
#http://localhost:8081/swagger-ui/index.html#/


